### ISSUE TITLE
救命！雅过敏！！

### ISSUE THREAD

**Issue by townechow** [sun0225SUN/Awesome-Love-Code#1]
完了完了
雅过敏了！🤣🤣

**Comment by sun0225SUN** [comment]
我还专门查了下”雅过敏“啥意思🙈

**Comment by xiayouran** [comment]
nice！请问下孙哥，绘制花的原理是什么，有相关函数公式吗

**Comment by sun0225SUN** [comment]
> nice！请问下孙哥，绘制花的原理是什么，有相关函数公式吗

对，因为图像是由像素点构成的，然后通过相应的拟合函数，点构成线，线构成面应该就可以绘制出来了。
我是参考的这位大佬的博客，https://blog.csdn.net/weixin_43387647/article/details/88956182，你可以研究下原理。
反正我是写不出来🤨

**Comment by xiayouran** [comment]
👍
